### ISSUE TITLE
[FEATURE] Add key bindings to mod config

### ISSUE THREAD

**Issue by ArchLinus** [SpaceWarpDev/SpaceWarp#102]
###### **Feature description**
Some mods need to have key bindings. It would be nice to have a common way for mods to have configurable key bindings, along with UI to input key bindings.

###### **Solution proposal**

 I'm not super familiar with how the new input system works in Unity, but it should probably be implemented in line with that. Perhaps mod config classes should be able to have InputBinding fields, and then they can create their own InputActions from these bindings.

Default values can be in line with the [Unity binding syntax](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/api/UnityEngine.InputSystem.InputControlPath.html), e.g. "\<Keyboard\>/space" or "\<Gamepad\>/buttonSouth".

Example config:

```cs
[ModConfig]
[JsonObject(MemberSerialization.OptOut)]
public class MyConfig
{
    [ConfigField("ShootKeyBind")]
    [ConfigDefaultValue("<Keyboard>/space")]
    public InputBinding ShootBinding;
}
```

**Comment by EwyBoy** [comment]
Key bindings already exist for mod configuration
BepInEx configuration adds it.
