### ISSUE TITLE
[FEATURE] Add specific game state messages that mods can subscribe to in space warp abstractions

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#104]
###### **Feature description**
KSP Provides an onGameStateChanged message, but this is a general message, we should have an abstraction of this for specific game states

###### **Solution proposal**
Add events that can be subscribed to for the following game states
- In main menu
- In VAB
- In Flight
- In Tracking Station
- In Overview
- Any other game states

**Comment by EwyBoy** [comment]
Was this fixed by #108 ?

**Comment by cheese3660** [comment]
Yes, should've closed this one
