### ISSUE TITLE
[FEATURE] Moving to BepInEx

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#105]
###### **Feature description**
It has become clear to me that BepInEx still provides things that we do not, and that there are still bugs in the BepInEx version of Space Warp, I would like to propose moving to BepInEx as a possible solution to this.

###### **Solution proposal**
1. We switch Space Warp to a fully BepInEx based plugin
2. Remove [MainMod]
3. Register mods with by searching through all plugins assemblies for classes that implement mod
5. Move all asset loading to the loading screen with the registered mod information, then provide event abstractions to the mod once assets have been loaded.
6. Keep our current GUI abstractions, and toolbar abstractions.
7. Remove the bespoke modloader
8. Keep a mods folder structure but move it into the mods plugin folder for BepInEx

This is only an idea, but I would like it to be discussed, as I feel as if it *could* be beneficial.

Another purpose to this change is that it could provide more direction to this project as we won't be doing 2 different things at once, one of which is reinventing the wheel.

This branch has been created in line with this issue
https://github.com/SpaceWarpDev/SpaceWarp/tree/experimental-bepinex-library

**Comment by adamsong** [comment]
I'd like to keep backwards compatibility as much as possible, but I do like the idea of transistioning

**Comment by jan-bures** [comment]
The sooner this gets done, the less pain in the long run, imo

**Comment by cheese3660** [comment]
Added the point of keeping the bespoke loader for backwards compatibility but deprecate it

**Comment by Halbann** [comment]
Could you elaborate on the reasons for 3 and 4?

**Comment by cheese3660** [comment]
Alright
For the reason for registering mods, we have the ability to reflect on all assemblies once BepInEx has loaded them, but I want to be able to register them as they load, and as such the best way is for them to be registered by the mod itself in the first stage initialization

As for the loading screen abstractions, users of mods will want to know assets are being loaded and all that and we don't want to provide a long freeze at the start of the game.

**Comment by gotmachine** [comment]
I think this is the most sensible approach. Bepinex is stable, maintained, and has a lot of useful features. Plus having SW as a library means it is ready for when an official modloader appears.

IMO, SW should aim to be the KSP2 middleman API of choice, providing a common framework for mods to build their features on. There is no no need for it to handle assembly loading/patching.

**Comment by EwyBoy** [comment]
> IMO, SW should aim to be the KSP2 middleman API of choice, providing a common framework for mods to build their features on. There is no no need for it to handle assembly loading/patching.

I completely agree with this! ⬆️

**Comment by Rexicon226** [comment]
agreed, still not too much done

**Comment by adamsong** [comment]
Also, CKAN has already decided to support BepInEx as the mod loader, and just use the compatibility mode for this

**Comment by cheese3660** [comment]
Going to edit with the following
- Remove backwards compatibility
- Make the [MainMod] not necessary
- Register on ChainLoad for mods
- Make a post about the folder structure

**Comment by gotmachine** [comment]
> Make a post about the folder structure

While you're at it, I would highly suggest to require that mods should be packaged as a single no-compression zip archive.
From experience, this can go a long way in avoiding user install errors, like putting stuff in the wrong subfolders, renaming mod folders, or the worst one, updating mods by dropping the new folder on the old one without deleting it first.

**Comment by gotmachine** [comment]
> That would require BepInEx to load zip files as plugins and can it do that?

Not out of the box, but I know its load process can be extended with a patcher, see https://github.com/BepInEx/BepInEx.MultiFolderLoader for an example.

**Comment by adamsong** [comment]
That would also require unity to load addressables from inside a zip.

**Comment by Halbann** [comment]
And how would plugins perform their own serialisation?

**Comment by cheese3660** [comment]
There own serialization?

**Comment by Halbann** [comment]
Lazy Orbit saves the menu that was last used by the player in a json next to the assembly.

**Comment by cheese3660** [comment]
It can still do that? I don't see the issue

**Comment by Halbann** [comment]
Ah, then maybe I don't understand what was meant by the proposal. Apologies.

**Comment by cheese3660** [comment]
If anyone wants to get started on making this happen, be my guest

**Comment by NathanPeake** [comment]
I don't really see the point in doing this. Both already work together.

seems like a useless change to me.

**Comment by cheese3660** [comment]
It allows for space warp dependent mods to use a lot of the abstractions bepinex provides.
It also resolves a lot of the confusion in the community about the differences in modloaders.
It also allows space warp itself to use BepInEx abstractions.

**Comment by cheese3660** [comment]
> If anyone wants to get started on making this happen, be my guest

Windows10CE has started on this it seems

**Comment by cheese3660** [comment]
> IMO, SW should aim to be the KSP2 middleman API of choice, providing a common framework for mods to build their features on. There is no no need for it to handle assembly loading/patching.

This is the point with this

**Comment by cheese3660** [comment]
Another note, I have not gotten any negative responses on the forum when referencing this issue

**Comment by cheese3660** [comment]
#107 is a draft PR for starting work on this.

**Comment by X606** [comment]
My one issue/thought on this is why remove the [MainMod] attribute? Thats there to give a clear entrypoint and let mods contain mod classes not intended to be loaded directly (theres tbf not that many reasons why you would want to do that but its nice to not lock people out of it),

**Comment by X606** [comment]
Plus, it breaks backwards compatibility for no reason

**Comment by adamsong** [comment]
Bepinex uses has [BepinPlugin] which does the same thing.

And updating the mods is easy.

**Comment by EwyBoy** [comment]
Merged PR #107 
https://github.com/SpaceWarpDev/SpaceWarp/tree/experimental-bepinex-library

**Comment by cheese3660** [comment]
This issue will remain open until we have a BepInEx release
