### ISSUE TITLE
[FEATURE] Colored spacewarp.console output depending on log level

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#119]
###### **Feature description**
To make looking into spacewarp.console easier, we should color output depending on log level.

###### **Solution proposal**
1. Color fatal errors in bright red
2. Color errors in red
3. Color warnings in yellow
4. Color messages in white
5. Color info in light gray
6. Color debug in dark gray

**Comment by EwyBoy** [comment]
Fixed in #122
