### ISSUE TITLE
[FEATURE] Add abstraction for disabling an app bar button

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#140]
###### **Feature description**
This is a clunky way of turning off an app bar button's indicator
```cs
GameObject.Find("BTN-ExampleMod")?.GetComponent<UIValue_WriteBool_Toggle>()?.SetValue(toggle);
```

###### **Solution proposal**
Add a `SetButtonIndicator(bool)` function to the appbar api that does this

**Comment by EwyBoy** [comment]
Merged in #160
