### ISSUE TITLE
[FEATURE] Linux installation guide

### ISSUE THREAD

**Issue by Myricaulus** [SpaceWarpDev/SpaceWarp#152]
###### **Feature description**
Currently this does not work on Linux machines at least not the same way it seem to work for others. If at all possible it would be cool to know what to do on a linux machine. When i try to use this via proton, the DLL does not seem to be loaded. So the menu options "mods" does not appear ingame and there is also no indication in Log files that something went wrong. Although there is a line stating "Modlog : Unable to locate the mods directory!" but it seem not be related to spacewarp as its still there after i remove every added file.

After some digging on BapInEx i found, that for wine it used to exists a hardpatcher of BapInEx, but i was unable to find it on their CI as mentioned on https://docs.bepinex.dev/articles/user_guide/installation/hardpatching.html .

I also tried version 0.3.0 as well as 0.4.0 without success. 

###### **Solution proposal**
Make a guide for linux users on how to get mods running.

###### **Additional context**
I run KSP2 on ubuntu 22.04 with proton.

###### **Screenshots / Images**
Ctrl + V here

**Comment by Windows10CE** [comment]
https://docs.bepinex.dev/articles/advanced/proton_wine.html

**Comment by EwyBoy** [comment]
Closing this issue as there is already documentation written for it.
