### ISSUE TITLE
[BUG] The plugins doesn't load

### ISSUE THREAD

**Issue by Pgabrielmnecraft** [SpaceWarpDev/SpaceWarp#159]
###### **KSP 2 Version**
0.1.0.0.20892

###### **Space Warp Version**
0.4.0

------------------------------

###### **Describe the bug**
The mods aren't loading in any circunstance.

###### **To Reproduce**
Just install BepInEx and SpaceWarp 0.4.0 and put your **UPDATED** mods on the plugins folder.

###### **Expected behavior**
I expected to the mods load.

###### **BepInEx Log**

[LogOutput.log](https://github.com/SpaceWarpDev/SpaceWarp/files/10903269/LogOutput.log)

**Comment by cheese3660** [comment]
Can you provide a screenshot of your mods folder and then the mods under them

**Comment by Pgabrielmnecraft** [comment]
> Can you provide a screenshot of your mods folder and then the mods under them

![image](https://user-images.githubusercontent.com/85260889/223245534-35f86ff0-a509-4a6c-ac10-d9cc0cce1f21.png)

**Comment by cheese3660** [comment]
Alright, now can you provide a screenshot of the inside of the configurationmanager folder?

**Comment by cheese3660** [comment]
I mean the uiscaler one

**Comment by cheese3660** [comment]
Alright, one other member has had this issue before, IIRC though they accidentally dragged the wrong spacewarp.dll into the folder, but that doesn't seem to be the case, what version did you upgrade from?

**Comment by EwyBoy** [comment]
This essentially boils down to https://github.com/SpaceWarpDev/SpaceWarp/labels/user%20error
Your folder structure should look like this inside the Kerbal Space Program 2 folder 📂
![image](https://user-images.githubusercontent.com/5883716/223390899-6d9f1e4e-7dc3-49b0-b238-08d208cab185.png)

Clean up your Kerbal Space Program 2 folder 📂 

Download the latest version of UI Scaler from here: [UI Scaler](https://spacedock.info/mod/3291/UI%20Scaler)
Download the latest version of Space Warp + BepInEx here: [Space Warp + BepInEx](https://spacedock.info/mod/3277/Space%20Warp%20+%20BepInEx)

Reinstall the mods and launch the game. It works flawlessly if you do it correct.

Closing this issue as this is **not** a Space Warp https://github.com/SpaceWarpDev/SpaceWarp/labels/bug
