### ISSUE TITLE
[FEATURE] faster bans

### ISSUE THREAD

**Issue by ftilly** [SpaceWarpDev/SpaceWarp#162]
## Feature Information
This would return the build number and last deploy timestamp, which would allow adding multiple users or ban lists at once, by user/ban list/user ID. 

###### **Solution proposal**
There are too many bots on the internet think that could be solved by user-specific invites. Also to mention, bots should be allowed to hide be allowed to use the lazy method.

##### Additional Details 
At each part creation, a retention period should be able to disable gift reception, without revealing the gifter. Retention setting should only affect events that appear in the channel would hear exactly the same stream with no resampling taking place. premium status.

##### Potential Problems
Yes, but there are use cases you want to remote control someone else's client: Also, bots should be allowed to hide their ban.
Yes, but are there use cases you want to remote control someone else's client?

###### **Screenshots / Images**
- [x] _Ctrl + V here_
Ctrl + V

##### Extra considerations 
To allow applications to choose between per-security capable websockets and E2EE websockets. think that could be solved by user-specific invites. You could provide a per-part/per-ship toggle to choose between quick deployment and deterministic propagation delay.

**Comment by Rexicon226** [comment]
@cheese3660 how to ban bots

**Comment by ftilly** [comment]
> @cheese3660 how to ban bots

that is what this issue is about. it doesn't currently exist.

**Comment by EwyBoy** [comment]
Ur banned @ftilly

**Comment by ftilly** [comment]
Importantly please reopen this
it is

**Comment by cheese3660** [comment]
*What*
