### ISSUE TITLE
[FEATURE] Completely move out of IMGui for Space Warp

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#170]
###### **Feature description**
Switch our UI windows from IMGui to unities UI assets

###### **Solution proposal**
Use our asset bundle loading system to load assetbundles for our space warp UIs, they can reference the scripts in the dll iirc so that wont be an issue.

###### **Additional context**
IMGui is meant for debugging and development and has not so great performance.

**Comment by cheese3660** [comment]
Note if we do this, then other things are unnecessary, but we should still provide the stockalike imgui skin

**Comment by jan-bures** [comment]
This is in progress, not using uGUI but the UITK for KSP 2 library (https://github.com/jan-bures/UitkForKsp2).

Progress:
- [x] Mod list
- [ ] Console
- [ ] Version check dialog

Issues to solve:

- [ ] Click through blocking
- [ ] Mod list: click event not activating on list items except for around the toggle
- [ ] Colors are lighter than they are supposed to be, UITK issue, not SpaceWarp-specific

**Comment by cheese3660** [comment]
Edited progress tracker

**Comment by cheese3660** [comment]
Now, just need to solve click through blocking

**Comment by cheese3660** [comment]
Moving click through blocking to separate issue, as the crux of this one has been solved
