### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lsamman** [SpaceWarpDev/SpaceWarp#178]
ksp 0.1.1

spacewarp 1.0

------------------------------

## Bug Information

mods work however appbar additions don't work

Steps to reproduce the behavior: cannot reproduce / cannot fix

###### **Expected behavior**
appbar appears without extra popout button

https://discord.com/channels/1078696971088433153/1078841771771056280/1085998544588115999 & https://discord.com/channels/1078696971088433153/1078841771771056280/1085998040600547418

**Comment by cheese3660** [comment]
Stage Info bug, not Space Wadp
