### ISSUE TITLE
[FEATURE] add info about installing for Steam/Proton  under Linux

### ISSUE THREAD

**Issue by michal2229** [SpaceWarpDev/SpaceWarp#179]
It seems that SpaceWarp does not work out of the box under Steam/Proton on Linux. There is need to set winhttp library as _native, builtin_ with winecfg/protontricks as mentioned [here](https://forum.kerbalspaceprogram.com/index.php?/topic/212355-bepinex-for-ksp-2-adding-modding-support-to-the-game/&do=findComment&comment=4259490). 
I think it would be nice to add this info to install instructions.

**Comment by EwyBoy** [comment]
Now, I won't lie to you, this isn't the craziest idea I've heard today, but it's definitely up there. However, we look into updating our documentation for this.

**Comment by cheese3660** [comment]
Its not that crazy, @Windows10CE for example uses linux

**Comment by jan-bures** [comment]
It's not that big of an ask - just add a link to [https://docs.bepinex.dev/articles/advanced/proton_wine.html](https://docs.bepinex.dev/articles/advanced/proton_wine.html)

**Comment by EwyBoy** [comment]
I'm just fooling around, its an easy fix. Hope we can get this sorted to make it easier for people on Linux to setup

**Comment by Rexicon226** [comment]
Just make en branch in the Docs repo :D

**Comment by Rexicon226** [comment]
@michal2229 Just modify the readme to your liking and then submit it to this pr. We'll look over it.

**Comment by michal2229** [comment]
> > @michal2229 Just modify the readme to your liking and then submit it to this pr. We'll look over it.
> 
> Added PR: #184

I see it was merged, thanks. Closing.
