### ISSUE TITLE
[BUG] Incorrectly Identifying Compatible Mod Versions

### ISSUE THREAD

**Issue by schlosrat** [SpaceWarpDev/SpaceWarp#182]
###### **KSP 2 Version**
0.1.1

###### **Space Warp Version**
1.0.1

------------------------------

###### **Describe the bug**
SpaceWarp is failing to correctly understand the min and max compatible KSP2 versions for mods. There are numerous mods (e.g., 
Community Fixes, Cheat Menu, Kerbal Part Manager, etc.) where the max compatible version is set to a value larger than 0.1.1 (e.g. 0.2.0) and yet spacewarp.modlist is showing them as "(unsupported)". The only mods I'm aware of that don't have this problem are using a max of either 1 or *.

###### **To Reproduce**
Select MOD menu at game stat or press Alt-M in the game. Click any SpaceWarp mod that's listed in red. Check the KSP2 version range.

###### **Expected behavior**
SpaceWarp should show mods where the current KSP2 version is bounded between the min and max values listed for the mod as being compatible.

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
N/A

###### **Screenshots**
Easily reproduced on any system

###### **Additional context**
Thanks! Love SpaceWarp and the mods that are available! Keep up the good work!

**Comment by cheese3660** [comment]
This is known about, and I will be looking into it

**Comment by Rexicon226** [comment]
fixed?

![image](https://user-images.githubusercontent.com/87927264/227349209-8a01d181-5b84-44bf-8fec-48ca00b0aa89.png)

**Comment by cheese3660** [comment]
Yes

**Comment by Rexicon226** [comment]
👍
