### ISSUE TITLE
[FEATURE] Add button to open mods folder

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#191]
###### **Feature description**
The mods folder is buried one layer deep in the ksp2 directory and is named plugins, we should add a way to open this folder in game.

###### **Solution proposal**
Add a button in the modlist UI to open up the BIE/Plugins folder

**Comment by Rexicon226** [comment]
i'll do it when i get home in an hour or so

**Comment by cheese3660** [comment]
Wait on this as the UI is being redone

**Comment by Rexicon226** [comment]
k np

**Comment by jan-bures** [comment]
added in #218
