### ISSUE TITLE
[BUG] Audio not working on v1.1.0

### ISSUE THREAD

**Issue by Dietz33** [SpaceWarpDev/SpaceWarp#201]
###### **KSP 2 Version**
The KSP 2 Version

###### **Space Warp Version**
The Space Warp Version 1.1.0

------------------------------

###### **Describe the bug**
Have no sound with 1.1.0 it works with the version before

###### **To Reproduce**
Steps to reproduce the behavior: start the game - no sound

###### **Expected behavior**
haviing sound

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
Ctrl + V here

**Comment by Falki-git** [comment]
I can confirm, no sound after upgrading to 1.1.0

**Comment by cheese3660** [comment]
This is known about, we are currently investigating

**Comment by cheese3660** [comment]
Fixed
