### ISSUE TITLE
[FEATURE] Show warning in main menu when SW detects an outdated mod

### ISSUE THREAD

**Issue by Falki-git** [SpaceWarpDev/SpaceWarp#214]
###### **Feature description**
Player loads the game, sees that there's a warning that some mods are outdated, he goes to the Mods section to see details.

###### **Solution proposal**
Show a warning icon in main menu next to the MODS item. Using colors would be nice; yellow usually means a warning (mods are outdated, but they could be working normally). Yellow triangle or circle.

###### **Screenshots / Images**
Example:
![image](https://user-images.githubusercontent.com/72734856/234416458-9ed7828c-5967-42e9-b010-f58ef6e0be95.png)

**Comment by Rexicon226** [comment]
This is implemented isn't it?

**Comment by Falki-git** [comment]
Yes, implemented with 1.4.0
