### ISSUE TITLE
[BUG] Mod Settings are missing when you exit to main menu

### ISSUE THREAD

**Issue by Falki-git** [SpaceWarpDev/SpaceWarp#276]
###### **KSP 2 Version**
0.2.0

###### **Space Warp Version**
1.6.0

------------------------------

###### **Describe the bug**
Mod Settings aren't available when you exit to main menu

###### **To Reproduce**
Load a campaign as normal, then exit to main menu. When you enter Settings -> Mods only UITK for KSP2 configs are present

###### **Expected behavior**
All mods that registered their configs are present

**Comment by jan-bures** [comment]
I can't replicate this

**Comment by Falki-git** [comment]
Ok, there are additional steps to reproduce is, or more precise - lack of steps.

1. Load the game
2. _**DON'T**_ go into settings, launch the campaign immediately
3. Exit to main menu
4. Go to Settings -> Mods
5. Only UITK for KSP 2 - UI Scaling is shown

![image](https://github.com/SpaceWarpDev/SpaceWarp/assets/72734856/572fc032-6f89-470f-90d3-3387ad334d4b)

**Comment by cheese3660** [comment]
Can I have logs from this?

**Comment by cheese3660** [comment]
Actually, I'll quickly try to replicate it

**Comment by jan-bures** [comment]
Fixed in #278
