### ISSUE TITLE
[BUG] 1.7.0 is not uploaded to CKAN

### ISSUE THREAD

**Issue by iL0g1c** [SpaceWarpDev/SpaceWarp#281]
###### **KSP 2 Version**
The KSP 2 Version: 0.2.0.0

###### **Space Warp Version**
The Space Warp Version: 1.7.0

------------------------------

###### **Describe the bug**
The most recent version of SpaceWarp is not uploaded to CKAN which is causing other mods like MicroEngineer to break.

###### **To Reproduce**
Open a KSP 2 instance in CKAN.
Click on SpaceWarp and go to versions.
SpaceWarp 1.7.0 is not listed.

###### **Expected behavior**
1.7.0 should be listed

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
This is the log error I got from BepinX when trying to load MicroEngineer
Could not load [MicroEngineer 1.7.0] because it has missing dependencies: com.github.x606.spacewarp (v1.7.0 or newer)

**Comment by cheese3660** [comment]
What version of CKAN are you using, spacewarp requires >= 1.34.2

**Comment by jan-bures** [comment]
To add onto that, nearly all newest versions of mods require that CKAN version.
