### ISSUE TITLE
[FEATURE] Update Modding Tutorial Wiki

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#36]
Modding Tutorial Wiki Needs To Be Updated

**Comment by EwyBoy** [comment]
Any progress on this issue? What is the current state?
If not done yet I would like to request a better description of what is needed to resolve this issue.
Perhaps a Checklist of what tasks need to be resolved:
- [ ] (for unchecked checkbox)
- [x] (for checked checkbox)

**Comment by EwyBoy** [comment]
After a quick look at the wiki, I would say that this issue is resolved as the wiki is updated with modding a lot of info and this issue does not really belong in this repository's issue tracker.
