### ISSUE TITLE
[FEATURE] Reload a mod without restarting

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#37]
Investigate mod reloading

**Comment by EwyBoy** [comment]
Is this a "do-not-fix", since we are no longer the mod loader?
Can this issue be closed at this point?

**Comment by ArchLinus** [comment]
BepInEx has support for mod reloading when using ScriptEngine plugin. The problem I'm seeing however is that the `BaseSpaceWarpPlugin.OnInitialized` method is not called when a mod is loaded through ScriptEngine. 

How ScriptEngine seems to work is that it will call the Awake method of your plugin directly on load. This bypasses the whole mod initialization process of SpaceWarp. 

Perhaps `BaseSpaceWarpPlugin.Awake` can check if the game is already initialized, and if so, call the mod's initialization methods?

**Comment by EwyBoy** [comment]
Not sure if this issue is valid anymore as we are not longer a mod loader? @cheese3660

**Comment by cheese3660** [comment]
I'd agree w/ that
