### ISSUE TITLE
[FEATURE] Built-in Click Through Blocker

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#49]
Given how many windows we have and such already, this merits investigation

**Comment by Rexicon226** [comment]
Started writing a ClickThroughBlocker class omfg its so long. For dealling with console log issues.

**Comment by EwyBoy** [comment]
Is this still being worked on and what's the status on this one?

**Comment by Rexicon226** [comment]
Still being worked on. Had to start over basically cuz of the move. xd

**Comment by EwyBoy** [comment]
"Merging" this into the master issue for the UI overhaul #127
