### ISSUE TITLE
Mods not persisting through "Quit to Main Menu"

### ISSUE THREAD

**Issue by Micrologist** [SpaceWarpDev/SpaceWarp#58]
Mod GameObjects (or rather all GameObjects) are subject to being removed when quitting to main menu thanks to the `DestroyAllGameObjectsFlowAction`.

Game Objects are only spared if they :
1. are the `GameManager` or
2. have a `DOTweenComponent` or
3. are tagged `"Game Manager"` or `"Graphics Manager"` (see `_dontDestroyTags`)

The two obvious ways to evade this destruction is to either tag your GameObjects as `"Game Manager"` or `"Graphics Manager"`, or to set your object's `hideFlags` to `HideFlags.HideAndDontSave` (or any other hide flag) so that the routine will not find your GameObjects.

Mods can theoretically implement either of these workarounds on their own, but it might be worth investigating a mod loader solution to have all mods persist through quitting to menu by default.

This could either be achieved by protecting the individual mod game objects or by just protecting the SpaceWarp object and making sure all mods get reinstantiated after loading into the main menu.

**Comment by cheese3660** [comment]
All right, all mod objects will be tagged in the future with "Game Manager" and there will be a space warp function to do so with other game objects

**Comment by cheese3660** [comment]
I'll make a fix for this soon

**Comment by Micrologist** [comment]
I'm wondering if there is any benefit in making the mods persistent vs. just having them reinstantiated again.
If you want to keep them alive then you have to worry about every object that mod may have created at runtime. (I'm assuming that is what you meant by having a space warp function for that, but I'm not sure what benefit that would have over the mods themselves setting the tags when they create an object)

I guess it comes down to whether or not its beneficial for mods to keep their state through quitting to menu and loading back into a save file.

**Comment by cheese3660** [comment]
I'll have them persist then add events in SpaceWarpManager to subscribe to

**Comment by cheese3660** [comment]
Look at that real quick

**Comment by Micrologist** [comment]
So the initial mod object will automatically be persistent (by having its tag set). If mods create any objects they want to be persistent they can pass them through `SpaceWarpManager.Persist`?

**Comment by cheese3660** [comment]
Yep!

**Comment by Micrologist** [comment]
alright, lgtm

**Comment by cheese3660** [comment]
Just need another maintainer to review the fix and I'll merge it

**Comment by cheese3660** [comment]
Fixed with #60
