### ISSUE TITLE
[FEATURE] Add Borders to UI

### ISSUE THREAD

**Issue by Rexicon226** [SpaceWarpDev/SpaceWarp#66]

**Comment by EwyBoy** [comment]
Was this done on 0.3?

**Comment by cheese3660** [comment]
Not yet

**Comment by EwyBoy** [comment]
Is this still being worked on and what is the status for this issue?

**Comment by EwyBoy** [comment]
Closing this issue and "merging" this into [FEATURE] Finishing UI assets #127 as a sub task to clean up the issue tracker.
