### ISSUE TITLE
[FEATURE] Switch around MainMenuPatcher to use an event subscriber and add an API for mods to add buttons on the main menu

### ISSUE THREAD

**Issue by cheese3660** [SpaceWarpDev/SpaceWarp#99]
###### **Feature description**
We have a patching system for the main menu, but it can only be used by space warp internally, it should be exposed in a way for mods to use it

###### **Solution proposal**
1. Change the harmony patcher to instead ping an event that mods can subscribe to
2. Have the Space Warp API subscribe to this ping
3. Add a method to the Space Warp API to register a menu button, that stores all registered buttons and adds them every time the main menu is opened by responding to the ping

**Comment by EwyBoy** [comment]
Was this issue resolved by #108 ?

**Comment by cheese3660** [comment]
Yes
